# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-01 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0049_auto_20200601_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added')),
                ('file_no', models.CharField(db_index=True, help_text='The file no.', max_length=128, unique=True, verbose_name='Label')),
                ('parties', models.CharField(db_index=True, default='', help_text='Involved parties.', max_length=512, verbose_name='Parties')),
                ('group', models.CharField(choices=[('none', 'None'), ('mota engil', 'Mota Engil'), ('pro bono', 'Pro Bono')], db_index=True, default='none', help_text='The group file no. belongs to.', max_length=48, verbose_name='Group')),
                ('status', models.CharField(choices=[('active', 'Active'), ('not active', 'Not active'), ('closed', 'Closed'), ('file transfered to client', 'File transfered to client')], db_index=True, default='not active', help_text='The status of the file no.', max_length=48, verbose_name='Status')),
                ('documents', models.ManyToManyField(to='documents.Document')),
                ('lawyers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('file_no',),
                'verbose_name': 'Register',
                'verbose_name_plural': 'Register',
            },
        ),
    ]
