# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-04 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='date',
            new_name='opened',
        ),
    ]
