# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-04 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200704_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='opened',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opened'),
        ),
    ]
