# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-17 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200704_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ('-opened',), 'verbose_name': 'Register', 'verbose_name_plural': 'Register'},
        ),
    ]
