# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-03-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0049_auto_20200601_1001'),
        ('register', '0004_auto_20201017_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opened')),
                ('file_no', models.CharField(db_index=True, help_text='The file no.', max_length=128, unique=True, verbose_name='Label')),
                ('parties', models.CharField(db_index=True, default='', help_text='Involved parties.', max_length=512, verbose_name='Parties')),
                ('status', models.CharField(choices=[('active', 'Active'), ('not active', 'Not active'), ('closed', 'Closed'), ('file transfered to client', 'File transfered to client')], db_index=True, default='not active', help_text='The status of the file no.', max_length=48, verbose_name='Status')),
                ('documents', models.ManyToManyField(to='documents.Document')),
            ],
            options={
                'ordering': ('-opened',),
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
            },
        ),
    ]
