# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-04-25 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='transfer_to',
            field=models.CharField(default='', help_text='Request to transfer to', max_length=512, verbose_name='Transfer to'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not active', 'Not active'), ('closed', 'Closed'), ('file transfered to client', 'File transfered to client'), ('request to close', 'Request to close'), ('request to transfer', 'Request to transfer')], db_index=True, default='not active', help_text='The status of the file no.', max_length=48, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not active', 'Not active'), ('closed', 'Closed'), ('file transfered to client', 'File transfered to client'), ('request to close', 'Request to close'), ('request to transfer', 'Request to transfer')], db_index=True, default='not active', help_text='The status of the file no.', max_length=48, verbose_name='Status'),
        ),
    ]
