# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-05-03 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210425_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ('-pk',), 'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ('-pk',), 'verbose_name': 'Register', 'verbose_name_plural': 'Register'},
        ),
        migrations.AddField(
            model_name='register',
            name='last_status',
            field=models.CharField(choices=[('active', 'Active'), ('not active', 'Not active'), ('closed', 'Closed'), ('file transfered to client', 'File transfered to client'), ('request to close', 'Request to close'), ('request to transfer', 'Request to transfer')], db_index=True, default='Not active', help_text='The last status of the file no.', max_length=48, verbose_name='Last Status'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not active', 'Not active'), ('closed', 'Closed'), ('request to close', 'Request to close'), ('request to transfer', 'Request to transfer')], db_index=True, default='not active', help_text='The status of the file no.', max_length=48, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='register',
            name='group',
            field=models.CharField(choices=[('active', 'Active'), ('not active', 'Not active'), ('closed', 'Closed'), ('file transfered to client', 'File transfered to client'), ('request to close', 'Request to close'), ('request to transfer', 'Request to transfer')], db_index=True, default='none', help_text='The group file no. belongs to.', max_length=48, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not active', 'Not active'), ('closed', 'Closed'), ('file transfered to client', 'File transfered to client'), ('request to close', 'Request to close'), ('request to transfer', 'Request to transfer')], db_index=True, default='Not active', help_text='The status of the file no.', max_length=48, verbose_name='Status'),
        ),
    ]
