# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-09-05 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20210519_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ('-opened', '-pk'), 'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
        migrations.AlterField(
            model_name='register',
            name='group',
            field=models.CharField(choices=[[b'---', b'---'], [b'Mota Engil', b'Mota Engil'], [b'Pro Bono', b'Pro Bono'], [b'General files', b'General files'], [b'Mwaiwathu', b'Mwaiwathu']], db_index=True, default='none', help_text='The group file no. belongs to.', max_length=48, verbose_name='Group'),
        ),
    ]
