# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-01-30 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20210905_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the client', max_length=256, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[[b'Active', b'Active'], [b'Not active', b'Not active'], [b'Closed', b'Closed'], [b'Request to close', b'Request to close'], [b'Request to transfer', b'Request to transfer']], db_index=True, default='not active', help_text='The status of the file no.', max_length=48, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='register',
            name='group',
            field=models.CharField(choices=[[b'---', b'---'], [b'Mota Engil', b'Mota Engil'], [b'Pro Bono', b'Pro Bono'], [b'Trademark', b'Trademark']], db_index=True, default='none', help_text='The group file no. belongs to.', max_length=48, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_status',
            field=models.CharField(choices=[[b'Active', b'Active'], [b'Dormant', b'Dormant'], [b'Not active', b'Not active'], [b'Closed', b'Closed'], [b'Transferred to client', b'Transferred to client'], [b'Request to close', b'Request to close'], [b'Request to transfer', b'Request to transfer']], db_index=True, default='Not active', help_text='The last status of the file no.', max_length=48, verbose_name='Last Status'),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[[b'Active', b'Active'], [b'Dormant', b'Dormant'], [b'Not active', b'Not active'], [b'Closed', b'Closed'], [b'Transferred to client', b'Transferred to client'], [b'Request to close', b'Request to close'], [b'Request to transfer', b'Request to transfer']], db_index=True, default='Not active', help_text='The status of the file no.', max_length=48, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='register',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Client', verbose_name='Client'),
        ),
    ]
