# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-01-31 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20220130_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Department', max_length=256, unique=True, verbose_name='Department')),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Department', verbose_name='Department'),
        ),
    ]
