# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-02-08 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20220131_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='cause_no',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='Cause Number'),
        ),
        migrations.AddField(
            model_name='register',
            name='court',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='Court'),
        ),
        migrations.AddField(
            model_name='register',
            name='opposing_parties',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='Opposing Parties'),
        ),
        migrations.AddField(
            model_name='register',
            name='other_parties',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='Other Parties'),
        ),
    ]
