# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-02-08 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20220208_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='opposing_parties',
            field=models.TextField(blank=True, default='', verbose_name='Opposing Parties'),
        ),
        migrations.AlterField(
            model_name='register',
            name='other_parties',
            field=models.TextField(blank=True, default='', verbose_name='Other Parties'),
        ),
    ]
