# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-02-27 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0013_auto_20220208_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='last_lawyers',
            field=models.ManyToManyField(related_name='last_lawyers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='register',
            name='group',
            field=models.CharField(choices=[[b'---', b'---'], [b'Mota Engil', b'Mota Engil'], [b'Pro Bono', b'Pro Bono'], [b'Trademark', b'Trademark'], [b'GA Recovery of outlay', b'GA Recovery of outlay'], [b'Audit Reports', b'Audit Reports'], [b'General and Non-Billable Files', b'General Non-Billable Files']], db_index=True, default='none', help_text='The group file no. belongs to.', max_length=48, verbose_name='Group'),
        ),
    ]
