# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-03-04 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20220227_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, help_text='Name and position of client contact person of client', max_length=256, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, help_text='Email of contact person of client', max_length=256, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, help_text='Telephon of contact person of client', max_length=256, verbose_name='Phone'),
        ),
    ]
