# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-03-06 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20220304_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the client', max_length=256, verbose_name='Name')),
                ('phone', models.CharField(blank=True, help_text='Telephon of contact person of client', max_length=256, verbose_name='Phone')),
                ('email', models.CharField(blank=True, help_text='Email of contact person of client', max_length=256, verbose_name='Email')),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='contact',
            new_name='contact_old',
        ),
        migrations.AddField(
            model_name='register',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='clients', to='register.Client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the client', max_length=256, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Client', verbose_name='Client'),
        ),
    ]
