# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-03-08 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20220306_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='register.Contact'),
        ),
    ]
