# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-03-24 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_register_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, help_text='Address', max_length=256, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, help_text='Address', max_length=256, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, help_text='Posittion of contact person of client', max_length=256, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='contact',
            name='town',
            field=models.CharField(blank=True, help_text='Address', max_length=256, verbose_name='Town'),
        ),
    ]
