# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-04-05 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_auto_20220324_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name used by other apps to reference this group. Do not use python reserved words, or spaces.', max_length=48, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Status of a matter', max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='groupf',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Group', verbose_name='GroupF'),
        ),
        migrations.AddField(
            model_name='register',
            name='statusf',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Status', verbose_name='StatusF'),
        ),
    ]
