# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-04-06 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_auto_20220405_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='_file_no_bak',
            field=models.CharField(default='', help_text='The file number', max_length=128, verbose_name='File Number'),
        ),
    ]
