# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-04-28 15:30
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_register__file_no_bak'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='background_color',
            field=colorful.fields.RGBColorField(default='#FFFFFF', help_text='The RGB background color value tor the status.', verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='status',
            name='color',
            field=colorful.fields.RGBColorField(default='#000000', help_text='The RGB font color value for the status.', verbose_name='Color'),
        ),
    ]
