# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-04-28 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0021_auto_20220428_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='group',
        ),
        migrations.RemoveField(
            model_name='register',
            name='groupf',
        ),
        migrations.RemoveField(
            model_name='register',
            name='status',
        ),
        migrations.RemoveField(
            model_name='register',
            name='statusf',
        ),
    ]
