# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-04-28 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_auto_20220428_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='client',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='register',
            name='client',
        ),
        migrations.RemoveField(
            model_name='register',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='register',
            name='contacts',
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Status', verbose_name='StatusF'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
