# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-04-28 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('register', '0023_auto_20220428_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='clients',
            field=models.ManyToManyField(blank=True, to='clients.Client'),
        ),
        migrations.AddField(
            model_name='register',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='clients.Contact'),
        ),
        migrations.AddField(
            model_name='register',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Group', verbose_name='Group'),
        ),
    ]
