# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-09-01 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_auto_20220428_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Status', verbose_name='StatusF'),
        ),
    ]
