# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-09-01 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_quotation__status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='status',
            new_name='status_old',
        ),
    ]
