# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-09-01 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_auto_20220901_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='_status',
            new_name='status',
        ),
    ]
