# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-09-19 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('register', '0027_auto_20220901_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferredRegisterFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retain_or_transfer', models.CharField(default='', max_length=256, verbose_name='Retain file or transfer required')),
                ('date_closure_letter', models.DateField(blank=True, null=True, verbose_name='Date of closure letter to client')),
                ('instructions', models.DateField(blank=True, null=True, verbose_name='Instructions received regarding file transfer')),
                ('date_completion', models.DateField(blank=True, null=True, verbose_name='Date of completion of transfer process')),
                ('notice', models.DateField(blank=True, null=True, verbose_name='Notice of change of legal practitioners')),
                ('receipt', models.DateField(blank=True, null=True, verbose_name='Receipt of file acknowledgement')),
                ('file_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='File to new lawyer or client')),
                ('files', models.ManyToManyField(to='register.Register')),
            ],
            options={
                'ordering': ('-date_closure_letter',),
                'verbose_name': 'Transferred Register File',
                'verbose_name_plural': 'Transferred Register Files',
            },
        ),
    ]
