# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-09-26 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_transferredregisterfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransferredRegisterFile',
            new_name='ActiveFileTrackingChart',
        ),
    ]
