# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-11-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_auto_20220926_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='physical_file_available',
            field=models.BooleanField(default=True),
        ),
    ]
