# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-08-14 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_register_physical_file_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='last_activity',
            field=models.CharField(default='', help_text='last_activity', max_length=512, verbose_name='last_activity'),
        ),
        migrations.AddField(
            model_name='register',
            name='retention_period',
            field=models.CharField(default='', help_text='Retention_period', max_length=512, verbose_name='Retention Period'),
        ),
        migrations.AddField(
            model_name='register',
            name='year_of_destruction',
            field=models.CharField(default='', help_text='year_of_destruction', max_length=512, verbose_name='year_of_destruction'),
        ),
    ]
