# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-08-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0031_auto_20240814_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='register',
            name='retention_period',
        ),
        migrations.RemoveField(
            model_name='register',
            name='year_of_destruction',
        ),
    ]
