# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-08-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0032_auto_20240820_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Activity'),
        ),
        migrations.AddField(
            model_name='register',
            name='retention_period',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retention Period'),
        ),
        migrations.AddField(
            model_name='register',
            name='year_of_destruction',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Year of Destruction'),
        ),
        migrations.AddField(
            model_name='register',
            name='carton_no',
            field=models.CharField(default='', help_text='Carton number file placed in', max_length=512, verbose_name='Carton Number'),
        ),
        migrations.AddField(
            model_name='register',
            name='closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed'),
        ),
        migrations.AddField(
            model_name='register',
            name='room',
            field=models.CharField(default='', help_text='Room archive', max_length=512, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status_old',
            field=models.CharField(choices=[('Active', 'Active'), ('Not active', 'Not active'), ('Closed', 'Closed'), ('Request to close', 'Request to close'), ('Request to transfer', 'Request to transfer')], db_index=True, default='not active', help_text='The status of the file no.', max_length=48, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Dormant', 'Dormant'), ('Not active', 'Not active'), ('Closed', 'Closed'), ('Transferred to client', 'Transferred to client'), ('Request to close', 'Request to close'), ('Request to transfer', 'Request to transfer')], db_index=True, default='Not active', help_text='The last status of the file no.', max_length=48, verbose_name='Last Status'),
        ),

    ]
