# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-08-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0033_auto_20240820_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='retention_period',
        ),
    ]
