# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-08-20 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0034_auto_20240820_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='retention_period',
            field=models.CharField(default='', help_text='Retention Period', max_length=512, verbose_name='Retention Period'),
        ),
    ]
