# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-26 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_auto_20170718_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermailer',
            name='signature',
            field=models.TextField(blank=True, verbose_name='Signature'),
        ),
    ]
