# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-17 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0013_auto_20200601_1001'),
        ('permissions', '0007_remove_role_is_selectable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0049_auto_20200601_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.TextField(blank=True, verbose_name='Metadata')),
                ('tags', models.TextField(blank=True, verbose_name='Tags')),
                ('permissions', models.TextField(blank=True, verbose_name='Permissions')),
                ('cabinets', models.TextField(blank=True, verbose_name='Cabinets')),
                ('last_modified', models.TextField(blank=True, verbose_name='Last Modified')),
                ('label', models.TextField(blank=True, verbose_name='Label')),
                ('register_no', models.TextField(blank=True, verbose_name='Register No')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
                ('document_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentType')),
                ('role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.Role')),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.SharedUploadedFile')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TempDocument',
                'verbose_name_plural': 'TempDocuments',
            },
        ),
    ]
