# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-18 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_remove_role_is_selectable'),
        ('sapitwa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_list', models.TextField(blank=True, verbose_name='OptionList')),
                ('role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='permissions.Role')),
            ],
            options={
                'verbose_name': 'RegisterOptions',
                'verbose_name_plural': 'RegisterOptions',
            },
        ),
    ]
