# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-03-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_remove_role_is_selectable'),
        ('sapitwa', '0003_listoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_list', models.TextField(blank=True, verbose_name='OptionList')),
                ('role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='permissions.Role')),
            ],
            options={
                'verbose_name': 'Quotation Options',
                'verbose_name_plural': 'Quotation Options',
            },
        ),
        migrations.AddField(
            model_name='tempdocument',
            name='quotation_no',
            field=models.TextField(blank=True, verbose_name='Quotation No'),
        ),
    ]
