# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-12-16 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapitwa', '0005_userstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
    ]
