# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-06-08 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_auto_20220428_1549'),
        ('sapitwa', '0006_auto_20211216_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdocument',
            name='register_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Register'),
        ),
    ]
