# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-05 10:37
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0047_auto_20180917_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-date_added',), 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/mayan-3.1.9/media/document_storage'), upload_to=documents.models.UUID_FUNCTION, verbose_name='File'),
        ),
    ]
