# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-01 10:01
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0048_auto_20190905_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/mayan-EDMSdocs/media/document_storage'), upload_to=documents.models.UUID_FUNCTION, verbose_name='File'),
        ),
    ]
