# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2025-06-15 15:27
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0050_auto_20240818_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/user/Projects/Mayan/media/document_storage'), upload_to=documents.models.UUID_FUNCTION, verbose_name='File'),
        ),
    ]
