# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-05 10:37
from __future__ import unicode_literals

import common.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20180429_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareduploadedfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/mayan-3.1.9/media/shared_files'), upload_to=common.models.upload_to, verbose_name='File'),
        ),
    ]
