# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-08-18 19:06
from __future__ import unicode_literals

import common.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20200601_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareduploadedfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/ben/Projects/Mayan/3.1.10/mayan-edms/media/shared_files'), upload_to=common.models.upload_to, verbose_name='File'),
        ),
    ]
