# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2025-06-15 15:27
from __future__ import unicode_literals

import common.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20240818_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareduploadedfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/user/Projects/Mayan/media/shared_files'), upload_to=common.models.upload_to, verbose_name='File'),
        ),
    ]
