# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-09-05 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0009_auto_20210905_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('template', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistTemplateEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='checklist.Checklist', verbose_name='Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Checklist')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Register')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterTemplateEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, db_index=True, help_text='The actual value stored in the template entry field for the matter.', null=True, verbose_name='Value')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter', to='register.Register', verbose_name='Register')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(default=0.0, verbose_name='Number')),
                ('symbol', models.CharField(default='', max_length=32, verbose_name='Symbol')),
                ('label', models.CharField(max_length=512, verbose_name='Label')),
                ('entry_type', models.CharField(choices=[('LB', 'Label'), ('TX', 'Text'), ('DO', 'Date'), ('DT', 'Datetime'), ('CB', 'Checkbox'), ('YN', 'Yes No'), ('TA', 'Textarea')], default='TX', max_length=2)),
                ('indent', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, default='', max_length=512, verbose_name='Help Text')),
                ('checklist', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='checklist.Checklist')),
            ],
        ),
        migrations.AddField(
            model_name='registertemplateentry',
            name='template_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.TemplateEntry', verbose_name='Template Entry'),
        ),
        migrations.AddField(
            model_name='checklisttemplateentry',
            name='template_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.TemplateEntry', verbose_name='Template Entry'),
        ),
    ]
