# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-08-18 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateentry',
            name='entry_type',
            field=models.CharField(choices=[('LB', 'Label'), ('TX', 'Text'), ('DO', 'Date'), ('DT', 'Datetime'), ('CB', 'Checkbox'), ('YN', 'Yes No'), ('TA', 'Textarea'), ('AD', 'ActiveDormant')], default='TX', max_length=2),
        ),
    ]
