# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_indexing', '0014_auto_20180823_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexinstancenode',
            name='value',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='Value'),
        ),
    ]
