# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-05 10:37
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import document_signatures.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_signatures', '0008_auto_20180429_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detachedsignature',
            name='signature_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/mayan-3.1.9/media/document_signatures'), upload_to=document_signatures.models.upload_to, verbose_name='Signature file'),
        ),
    ]
