# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-01 10:01
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import document_signatures.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_signatures', '0009_auto_20190905_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detachedsignature',
            name='signature_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/mayan-EDMSdocs/media/document_signatures'), upload_to=document_signatures.models.upload_to, verbose_name='Signature file'),
        ),
    ]
