# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-08-18 19:06
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import document_signatures.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_signatures', '0010_auto_20200601_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detachedsignature',
            name='signature_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/ben/Projects/Mayan/3.1.10/mayan-edms/media/document_signatures'), upload_to=document_signatures.models.upload_to, verbose_name='Signature file'),
        ),
    ]
