# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2025-06-15 15:27
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import document_signatures.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_signatures', '0011_auto_20240818_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detachedsignature',
            name='signature_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/user/Projects/Mayan/media/document_signatures'), upload_to=document_signatures.models.upload_to, verbose_name='Signature file'),
        ),
    ]
