# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-05-08 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroptions',
            name='display_closed_register_files',
            field=models.BooleanField(default=False, verbose_name='Display closed register files.'),
        ),
    ]
