# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-09-26 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0029_auto_20220926_0843'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retain_or_transfer', models.CharField(blank=True, choices=[('', ''), ('RT', 'Retain file'), ('TR', 'Transfer required')], default='', max_length=2, verbose_name='Retain file or transfer required')),
                ('closure_letter', models.DateField(blank=True, null=True, verbose_name='Date of closure letter to client')),
                ('instructions', models.DateField(blank=True, null=True, verbose_name='Date instructions received regarding file transfer')),
                ('completion', models.DateField(blank=True, null=True, verbose_name='Date of completion of transfer process')),
                ('notice', models.DateField(blank=True, null=True, verbose_name='Date of notice of change of legal practitioners')),
                ('receipt', models.DateField(blank=True, null=True, verbose_name='Date of receipt of file acknowledgement')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='File to new lawyer or client')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Register', verbose_name='Tracked File')),
            ],
            options={
                'ordering': ('-closure_letter',),
                'verbose_name': 'Tracked Register File',
                'verbose_name_plural': 'Tracked Register Files',
            },
        ),
    ]
