# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2024-08-18 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackedfile',
            options={'ordering': ('-file__opened',), 'verbose_name': 'Tracked Register File', 'verbose_name_plural': 'Tracked Register Files'},
        ),
        migrations.AlterField(
            model_name='trackedfile',
            name='retain_or_transfer',
            field=models.CharField(blank=True, choices=[('', ''), ('RT', 'Retain'), ('TR', 'Transfer')], default='', max_length=2, verbose_name='Retain file or transfer required'),
        ),
    ]
