# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-04-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=256, verbose_name='City')),
                ('phone', models.CharField(blank=True, max_length=256, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=256, verbose_name='Email')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Name')),
                ('position', models.CharField(blank=True, help_text='Posittion of contact person of client', max_length=256, verbose_name='Position')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=256, verbose_name='City')),
                ('country', models.CharField(blank=True, help_text='Address', max_length=256, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=256, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=256, verbose_name='Email')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Client')),
                ('clients', models.ManyToManyField(blank=True, related_name='clients', to='clients.Client')),
            ],
        ),
    ]
