# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-09-29 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_ex_lawyer',
            field=models.BooleanField(default=False, verbose_name='Is an external lawyer'),
        ),
    ]
