# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-07 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_role_is_selectable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_selectable',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether or not this Role is shown in the list of roles one can share a document with.', verbose_name='Is selectable?'),
        ),
    ]
