# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_auto_20190407_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(default='', max_length=64, verbose_name='Type'),
        ),
    ]
