# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-16 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_role_role_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_selectable',
        ),
    ]
